import type { Metadata } from "next";
import { Inter, Newsreader } from "next/font/google";
import QueryProvider from "./QueryProvider";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import "./globals.css";
import AnnouncementBar from "./components/layout/AnnouncementBar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const newsreader = Newsreader({
  subsets: ["latin"],
  variable: "--font-newsreader",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${newsreader.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <AnnouncementBar />
          <Header />

          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
